dist: precise
language: ruby
cache:
  bundler: true
addons:
  apt:
    packages:
    - hunspell
    - libhunspell-dev
    - hunspell-en-us
rvm:
- 2.4.1
git:
  depth: 1
branches:
  only: develop
before_install:
- git config --global submodule.recurse true
- git config --global submodule.fetchJobs 8
before_deploy:
- bundle exec rake spell_check
- openssl aes-256-cbc -K $encrypted_b0cfc79abf17_key -iv $encrypted_b0cfc79abf17_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
    provider: script
    script: bash _scripts/deploy.sh
    skip_cleanup: true
    on:
       branch: develop
